# server
server:
  port: 8081

#spring:
#  application:
#    name: spring-gitlab-oauth

# logging
logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

# oauth2
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          gitlab:
#            client-id: 5ef753866e803eb90937f544c9bec311cb725fb687e914e1b9dcef8207d93044
#            client-secret: gloas-eef3a6403f620be41efafb5cfaecca78e7b0983fe628df49fe8a11ffb0340ca5
#            scope: read_user,profile,openid,email
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8081/login/oauth2/code/gitlab
#        provider:
#          gitlab:
#            authorization-uri: https://gitlab.com/oauth/authorize
#            token-uri: https://gitlab.com/oauth/token
#            user-info-uri: https://gitlab.com/api/v4/user
#            jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
#            user-name-attribute: preferred_username
